// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package widgets

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AddEventTabs(email string, isAdmin bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-white rounded-lg shadow-sm border border-gray-100 p-4 max-w-md mx-auto\"><!-- Переключатели --><div class=\"flex space-x-2 mb-4 border-b border-gray-200\"><button type=\"button\" onclick=\"showForm('status')\" id=\"tab-status\" class=\"pb-2 px-3 text-sm font-medium text-blue-600 border-b-2 border-blue-600 whitespace-nowrap\">Статус</button> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isAdmin {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<button type=\"button\" onclick=\"showForm('time')\" id=\"tab-time\" class=\"pb-2 px-3 text-sm font-medium text-gray-500 hover:text-gray-700 border-b-2 border-transparent whitespace-nowrap transition-colors\">Время</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><!-- Формы --><div id=\"form-status\" class=\"block\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = AddStatus(email).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isAdmin {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div id=\"form-time\" class=\"hidden\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = AddTimeEvent(email).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><script>\n    function showForm(tab) {\n        const formStatus = document.getElementById('form-status');\n        const formTime = document.getElementById('form-time'); // может быть null\n        const tabStatus = document.getElementById('tab-status');\n        const tabTime = document.getElementById('tab-time');     // может быть null\n\n        // Скрываем формы\n        formStatus.classList.add('hidden');\n        if (formTime) formTime.classList.add('hidden');\n\n        // Сбрасываем активный стиль (если элементы существуют)\n        if (tabStatus) {\n            tabStatus.classList.replace('text-blue-600', 'text-gray-500');\n            tabStatus.classList.replace('border-blue-600', 'border-transparent');\n        }\n        if (tabTime) {\n            tabTime.classList.replace('text-blue-600', 'text-gray-500');\n            tabTime.classList.replace('border-blue-600', 'border-transparent');\n        }\n\n        // Активируем нужную вкладку\n        if (tab === 'status' && tabStatus) {\n            formStatus.classList.remove('hidden');\n            tabStatus.classList.replace('text-gray-500', 'text-blue-600');\n            tabStatus.classList.replace('border-transparent', 'border-blue-600');\n        } else if (tab === 'time' && tabTime && formTime) {\n            formTime.classList.remove('hidden');\n            tabTime.classList.replace('text-gray-500', 'text-blue-600');\n            tabTime.classList.replace('border-transparent', 'border-blue-600');\n        }\n    }\n\n    // Инициализация\n    document.addEventListener('DOMContentLoaded', () => {\n        showForm('status');\n    });\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
