// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "strings"

type UserProfileProps struct {
}

func UserProfile() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		email := ctx.Value("email").(string)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- <div class=\"p-3 border-b border-gray-200 bg-gray-50\"> --><!-- \t<div class=\"mb-4\"> --><!-- \t\t<p class=\"font-medium mb-2 text-gray-900 text-sm truncate\">{ email }</p> --><!-- \t\t<div class=\"flex items-center justify-between\"> --><!-- \t\t\t<span class=\"text-xs text-gray-400\">Ведущий инженер</span> --><!-- \t\t\t<span class=\"text-xs text-amber-600\">В отпуске</span> --><!-- \t\t</div> --><!-- \t</div> --><!-- \t<div class=\"border-t border-gray-200 text-xs mb-6\"> --><!-- \t\t<p class=\"text-gray-600 font-medium mb-2\">Активные проекты:</p> --><!-- \t\t<ul class=\"space-y-2\"> --><!-- \t\t\t<li class=\"text-gray-700\"><a class=\"cursor-pointer\" href=\"#\">Усть луга</a> </li> --><!-- \t\t\t<li class=\"text-gray-700\">• Уренгой</li> --><!-- \t\t</ul> --><!-- \t</div> --><!-- </div> --><div class=\"p-4 border-t border-gray-200\"><div class=\"flex items-center mb-3\"><div class=\"w-10 h-10 bg-gradient-to-r from-blue-500 to-indigo-600 rounded-full flex items-center justify-center\"><span class=\"text-white font-semibold text-sm\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(strings.ToUpper(email)[0])
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/users_pofile.templ`, Line: 31, Col: 78}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></div><div class=\"ml-3\"><p class=\"text-sm font-medium text-gray-900\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(email)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/users_pofile.templ`, Line: 34, Col: 56}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p><p class=\"text-xs text-gray-500\">Ведущий инженер</p></div></div><div class=\"text-xs text-gray-600 mb-3\"><p class=\"font-medium mb-1\">Активные проекты:</p><ul class=\"space-y-1\"><li class=\"flex items-center\"><span class=\"w-2 h-2 bg-green-400 rounded-full mr-2\"></span> <span>Усть луга</span></li><li class=\"flex items-center\"><span class=\"w-2 h-2 bg-blue-400 rounded-full mr-2\"></span> <span>Уренгой</span></li></ul></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
